# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obei.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nobei.proto\x12\x04obei\"\'\n\x05jsStr\x12\x0e\n\x06jscode\x18\x01 \x01(\t\x12\x0e\n\x06\x63ookie\x18\x02 \x01(\t\"\x16\n\x03ret\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x07Greeter\x12\x31\n\x15obeiHKIIUU9O618PPTHPM\x12\x0b.obei.jsStr\x1a\t.obei.ret\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'obei_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JSSTR']._serialized_start=20
  _globals['_JSSTR']._serialized_end=59
  _globals['_RET']._serialized_start=61
  _globals['_RET']._serialized_end=83
  _globals['_GREETER']._serialized_start=85
  _globals['_GREETER']._serialized_end=145
# @@protoc_insertion_point(module_scope)
